export enum AuditAction {
  EXPENSE_CREATED = 'EXPENSE_CREATED',
  EXPENSE_SUBMITTED = 'EXPENSE_SUBMITTED',
  EXPENSE_APPROVED = 'EXPENSE_APPROVED',
  EXPENSE_REJECTED = 'EXPENSE_REJECTED',
  EXPENSE_REIMBURSED = 'EXPENSE_REIMBURSED',
  EXPENSE_REOPENED = 'EXPENSE_REOPENED',
  EXPENSE_COMMENT_ADDED = 'EXPENSE_COMMENT_ADDED',
  POLICY_VIOLATION = 'POLICY_VIOLATION',
  DELEGATION_CREATED = 'DELEGATION_CREATED',
  DELEGATION_REVOKED = 'DELEGATION_REVOKED',
  DEPARTMENT_MANAGER_CHANGED = 'DEPARTMENT_MANAGER_CHANGED',
  USER_DEPARTMENT_CHANGED = 'USER_DEPARTMENT_CHANGED',
  USER_SUSPENDED = 'USER_SUSPENDED',
  ROLE_PERMISSIONS_CHANGED = 'ROLE_PERMISSIONS_CHANGED',
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
}

export enum AuditResourceType {
  EXPENSE = 'EXPENSE',
  POLICY = 'POLICY',
  DELEGATION = 'DELEGATION',
  DEPARTMENT = 'DEPARTMENT',
  USER = 'USER',
  ROLE = 'ROLE',
}
