export enum NotificationType {
  EXPENSE_SUBMITTED = 'EXPENSE_SUBMITTED',
  EXPENSE_APPROVED = 'EXPENSE_APPROVED',
  EXPENSE_REJECTED = 'EXPENSE_REJECTED',
  EXPENSE_PENDING_FINANCE = 'EXPENSE_PENDING_FINANCE',
  EXPENSE_ESCALATED = 'EXPENSE_ESCALATED',
  EXPENSE_REIMBURSED = 'EXPENSE_REIMBURSED',
  BUDGET_OVERSPEND = 'BUDGET_OVERSPEND',
  BUDGET_THRESHOLD = 'BUDGET_THRESHOLD',
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  USER_DEPARTMENT_CHANGED = 'USER_DEPARTMENT_CHANGED',
  DEPARTMENT_MANAGER_CHANGED = 'DEPARTMENT_MANAGER_CHANGED',
  EXPORT_READY = 'EXPORT_READY',
  USER_SUSPENDED = 'USER_SUSPENDED',
}

export enum NotificationChannel {
  EMAIL = 'EMAIL',
  IN_APP = 'IN_APP',
}

export enum NotificationStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
}
